### ISSUE TITLE
Motion stops working, overlay not responding

### ISSUE THREAD

**Issue by wickles** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#181] opened 2019-04-25 18:09 UTC
Sometimes after spending some time in VRC my motion bindings will stop working, and when I open the Advanced Settings overlay the interface is frozen and unresponsive. If I wait I think it usually becomes responsive again after a while, sometimes I just kill it from taskman and restart the exe. 

Is there any debug logging I can enable to see what's causing it to become unresponsive?

**Comment by ykeara** [comment] 2019-04-25 18:15
Cool I get the issue too, have been putting off addressing it because figured it might just be my hardware config for w/e reason.

We do have logging... but it doesn't pick up on w/e the issue is... If you can post your HMD, OS, Specs (RAM/CPU/GPU)... and a description of what causes it would be appreciated.... if its re-create-able on your end I would love to know as well.

**Comment by wickles** [comment] 2019-04-25 23:28
I have an Oculus Rift, 8700k, RTX 2070. No idea what causes it, just happens every now and then, once every few days or so. If/when it happens again I will try and figure out if I was doing anything unusual that might be causing it.

**Comment by ykeara** [comment] 2019-04-25 23:43
Yea will start adding some more aggressive logging and such and see if we can find out what it is.... its a long way out though as we are a bit unsure what could be causing it.

**Comment by wickles** [comment] 2019-04-26 06:49
I can add two more details that might be helpful. I never experienced this issue before 3.0. And with 3.0 I switched from installing to a user directory, to installing to Program Files with the installer.

**Comment by Yinkai15** [comment] 2019-06-25 04:22
This happens to me about every 20-30 minutes.  I use push to talk and motion stuff.  Advanced VR will basically lock up for 2-5 minutes and I can't use either function.  Has there been any more progress on fixing this bug?  Anyway I can help by posting logs?  It's made Advanced VR borderline unusable for me recently.

**Comment by ykeara** [comment] 2019-06-25 06:11
Yea its not going to make 3.2.0 but will be working on it next is plan..... not 100% sure the cause, but fairly confident... that will get most of it mitigated quickly

**Comment by ykeara** [comment] 2019-08-23 20:37
https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/builds/26923372/job/ue4g5mv0fne48qao/artifacts okay this build Should contain some extra logging if you are seeing this issue It records at several entry points if there is a delay longer than ~5 seconds...... if you experience the issue please run this build and put a pastebin up of the logs after the program has recovered from the delay. (i.e. you will need to wait for program to start responding again before exiting.

**Comment by ykeara** [comment] 2019-10-21 03:39
Closing out for now, Issue seems to be resolved in newer versions. cause and solution are unknown, but no new reports, assuming it was resolved in an update we did or a SteamVR update.

**Closed by ykeara** 2019-10-21 03:39 UTC
Labels: Waiting Response, bug
