### ISSUE TITLE
chaperone visibility only goes down to 50%

### ISSUE THREAD

**Issue by Krylke** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#186] opened 2019-04-29 23:58 UTC

**Comment by Krylke** [comment] 2019-04-30 00:00
I usually have visibility set to around 20%. A minimum of 50% is way to much. It needs to go lower

**Comment by ykeara** [comment] 2019-04-30 00:01
I'll look and see If I can't figure out the exact minimum value.... I think it might be 30% but will have to play with it a bit.

**Comment by Krylke** [comment] 2019-04-30 02:23
Why cant the minimum just be 0% or 10%? Just make it that and everybody is happy :-)

**Comment by ykeara** [comment] 2019-04-30 02:36
It's a safety feature API use to let you take it to 0, but they didn't like it they capped it.... I think at 30% but im not sure that there is a solid number.

**Comment by soraryu** [comment] 2019-05-02 09:58
So you're saying that AdvancedSettings (or even SteamVR) doesn't support setting it to 0 anymore?
This is the main reason I'm using it. Are you in contact with SteamVR team to talk about that? We're using that for tradeshows etc, in very controlled environments, and clients are complaining about the "return of the thin circle line".

**Comment by ykeara** [comment] 2019-05-02 16:24
yes they limited the minimum opacity via the API, if you need the chaperone disabled run room setup (even if you are like going over objects so you can get minimum space) and then just set fade distance -> 0 OR click the disable button. (it just sets fade distance ->0) I will have to play around with some standing only set-ups to see if I can get things working better in standing only.

**Comment by Krylke** [comment] 2019-05-03 04:18
If I install the old 2.5 version it still works to go all the way down to zero so what you are saying cant be right.

**Comment by ykeara** [comment] 2019-05-03 05:01
That is interesting, and I will double check, but its probably because of the libraries packaged with 2.5 which are severely out of date and don't support many features -> new input, motion smoothing to name a few. It was 100% not working when I changed it.....


Should be noted are you using strictly openVR or are you using steam/SteamVR as well?

**Comment by Krylke** [comment] 2019-05-03 06:11
Im using steam vr

**Comment by soraryu** [comment] 2019-05-03 08:29
Same here, using SteamVR. I can confirm that it can be hidden by using full roomscale instead of standing, however, would be great to get the ability to hide the standing outline back.

**Comment by ykeara** [comment] 2019-05-04 00:52
yea 30% is minimum have adjusted will be in next PR. Issue will stay open until then.

**Closed** 2019-05-18 16:33 UTC
Labels: bug
