### ISSUE TITLE
Crashes When SteamVR Exits

### ISSUE THREAD

**Issue by GT500org** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#89] opened 2019-02-28 01:50 UTC
Crash dump:
https://www.gt500.org/debug/openvr-advancedsettings/2019-Feb-27/AdvancedSettings.exe.2888.dmp.7z

Every time I close SteamVR, AdvancedSettings.exe crashes. The only real nuisance is the amount of crash dumps that get saved, and the fact that WER automatically saving the dump keeps SteamVR from exiting for an extra minute or two.

OS = Win 10 (64-bit) 1809
Latest updates installed (as of the time of this post).
Windows Defender disabled.
Only other security software installed at the time the above dump was saved was GlassWire, which does not appear to open hooks to other running processes (checked using Process Hacker).

**Comment by username223** [comment] 2019-03-01 21:17
Thanks for the detailed bug report.

I pushed a fix for the problem on a separate branch. If you have the time it would be awesome if you could confirm that the problem is fixed by downloading the portable version from [here](https://ci.appveyor.com/project/icewind1991/openvr-advancedsettings/build/job/jsr1ag2nd2knwgqk/artifacts).

You can also download the installer version above and use that full time if you want but keep in mind that it is a development build and that not all new features are completely polished yet.

If the above fix works then it will be fixed in the next release (3.0.0).

**Comment by GT500org** [comment] 2019-03-02 04:44
I just tried your dev build, and this issue seems to be resolved. I launched SteamVR, opened OpenVR-AdvancedSettings, and exited SteamVR twice without a crash dump being written.

**Comment by username223** [comment] 2019-03-02 08:18
Cool, thanks for the swift response. The fix will be in the next release.

**Closed** 2019-03-02 08:45 UTC
Labels: bug
