### ISSUE TITLE
Advanced Settings: AdvancedSettings.exe - Application Error

### ISSUE THREAD

**Issue by Bluscream** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#366] opened 2020-02-25 12:40 UTC
**Describe the bug**
A crash:
```
---------------------------
Advanced Settings: AdvancedSettings.exe - Application Error
---------------------------
The instruction at 0x00007FFECDCAE45D referenced memory at 0x00000000000001F0. The memory could not be read.


Click on OK to terminate the program
Click on CANCEL to debug the program
---------------------------
OK   Cancel   
---------------------------
```

**To Reproduce**
1. Play around with motion keybinds

**Expected behavior**
No crash

**Screenshots**
![image](https://user-images.githubusercontent.com/3318223/75248294-34e00000-57d4-11ea-914f-bd8a6e76928c.png)

**Software (please complete the following information):**
 - OS:  Win 10.0.18363.657
 - Advanced Settings Version: 1.7.?

**Hardware (please complete the following information):**
 - CPU: AMD FX 4300
 - Graphics Card: NVidia GTX 1050Ti
 - HMD: Oculus Quest

**Additional context**
idk

**Comment by username223** [comment] 2020-02-25 15:39
Thank you for the issue.

Could you DL and install [this](https://ci.appveyor.com/api/buildjobs/yifpx2k2ef1c88yg/artifacts/installer%2FAdvancedSettings-4.0.1-dev%2B827d46e4-Installer.exe) version to ensure that the issue is still present in the current master?

**Comment by Bluscream** [comment] 2020-02-25 15:44
I am using that version already

**Comment by username223** [comment] 2020-02-25 15:52
Alright.

Please delete all files in the `%localappdata%/crashdumps` directory, then install and run [this](https://ci.appveyor.com/api/buildjobs/xl4edadwekqtqo3x/artifacts/installer%2FAdvancedSettings-4.0.1-dev%2B3d7867de-Installer.exe) version and when it crashes, upload the resulting `.dmp` file along with the log file from `%appdata%\AdvancedSettings-Team`.

**Comment by Bluscream** [comment] 2020-02-25 15:57
I've got these already, but i'll also try the one you just gave me
[CrashDumps.zip](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/4250902/CrashDumps.zip)

**Comment by username223** [comment] 2020-02-25 18:11
The last version I gave you had debug symbols enabled. 
Without those I can't know where the error occurs on our end.

The SEGFAULT appears in `vrclient_x64.dll`, but I don't know where our call site is because Windows won't load debug symbols for `AdvancedSettings.exe`.

Could you delete all crashdumps and then try again using [this (7z version now)](https://ci.appveyor.com/api/buildjobs/yifpx2k2ef1c88yg/artifacts/bin%2Fwin64%2FAdvancedSettings-4.0.1-dev%2B827d46e4.7z) exact binary?
I would also like logs from `%appdata%\AdvancedSettings-Team`.

**Comment by Bluscream** [comment] 2020-02-26 07:59
[CrashDumps.zip](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/4254158/CrashDumps.zip)

This is all reproduced with the new 7z version you gave me

**Comment by username223** [comment] 2020-02-26 08:36
Are you sure you were using the 7z version?

The logs report `Version 4.0.1-dev+827d46e4` which is the initial version and Windows won't recognize the 7z binary for the crashdump.

**Comment by Bluscream** [comment] 2020-02-26 09:31
![image](https://user-images.githubusercontent.com/3318223/75331485-16850d80-5883-11ea-8416-8215bdbc900d.png)

**Comment by username223** [comment] 2020-02-26 11:58
I'm still not getting any debug information.

Could you paste your SteamVR version info from `Help -> About SteamVR` and list exactly which steps you're taking to make it crash? I'll have to try to reproduce it here instead.

Which controllers are you using, do they have any visible firmware version?

___

The crash happens in `vrclient_x64.dll`. This is a binary blob distributed by SteamVR. It changes with each SteamVR version and I have not been able to find debug files for it, or any source code for it.

**Comment by username223** [comment] 2020-02-26 12:13
My bad, it seems like I've given you the wrong version.

Try [this](https://ci.appveyor.com/api/buildjobs/xl4edadwekqtqo3x/artifacts/bin%2Fwin64%2FAdvancedSettings-4.0.1-dev%2B3d7867de.7z) and upload logs/crashdumps.

**Comment by Bluscream** [comment] 2020-02-26 16:06
xD okay

**Comment by username223** [comment] 2020-02-27 10:54
@Bluscream I would still like dumps/logs if you have the time. :)

**Comment by Bluscream** [comment] 2020-02-27 12:03
Yeah, im gonna post them as soon as im in vr again

**Comment by username223** [comment] 2020-03-15 18:59
@Bluscream Do you have any logs/dumps?

I'll close this in 10 days if no further information is obtainable.

**Comment by Bluscream** [comment] 2020-03-15 20:44
Thanks for reminding me, i totally forgot about it ^.^

**Comment by username223** [comment] 2020-03-28 09:18
Closed due to no further information.

**Closed by username223** 2020-03-28 09:18 UTC
Labels: bug
