### ISSUE TITLE
OpenVR not opening at all

### ISSUE THREAD

**Issue by impledob** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#235] opened 2019-06-29 18:49 UTC
When i pull up the steam vr overlay and click advance settings nothing comes up. it's just the blank screen. i've tried re installing open vr on 3 different versions and re installing steam vr and all vive software.

**Comment by username223** [comment] 2019-06-30 09:58
What is your:
* OS
* CPU / GFX Card
* Driver versions
* SteamVR Version

**Comment by ykeara** [comment] 2019-06-30 16:10
sounds like original issue in #209 

try:
 Okay possible solution Is to go to NVidia control panel (AMD might have equiv?) and go to manage 3d Settings and add Advanced Settings as a program and force it to run on your GPU. See if that works might not but worth a shot....

**Comment by ykeara** [comment] 2019-07-04 02:54
Closing because probable duplicate of #209

**Closed by ykeara** 2019-07-04 02:54 UTC
Labels: Waiting Response
