### ISSUE TITLE
DiRT Rally's camera position is messed up (using Revive)

### ISSUE THREAD

**Issue by Xodetaetl** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#290] opened 2019-09-06 15:53 UTC
When OVR Advanced Settings is installed (at least with the couple last versions), DiRT Rally through Revive will center the world on the room center instead of the headset. When using the in-game button to recenter, the scene centers on the player for a split second then goes back to the center of the room.

I've seen many people report the issue on the Steam forums and Reddit.

Let me know if you want a Steam key of the game.

**Comment by ykeara** [comment] 2019-09-06 20:31
Duplicate of #170

closing in favor of consolidation. 

2.8.0 or older should work fine. It's an issue w/ different types of environments ("standing only" vs "roomscale") and different platforms.... but its an issue w/  `workingsetpreview` its my current priority.

**Closed by ykeara** 2019-09-06 20:31 UTC
Labels: bug
