### ISSUE TITLE
Offsets not saving

### ISSUE THREAD

**Issue by cappaholic** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#227] opened 2019-06-17 02:06 UTC
I'm coming from Advanced Settings 2.5, which worked fine. I would save the play area, name it, then be able to load it any time I started SteamVR.

With the latest version, the play area (offset?) does not load. The only way to get it to load is change a value on the offset page for room rotation, then apply, then reset all values on that page back to "0". Then the X, Y, and Z I saved are loaded.

WMR (Dell Visor)
Win10 
SteamVR 1.5.8

**Comment by ykeara** [comment] 2019-06-23 23:36
I'll look into it here in the next few days.

**Comment by ykeara** [comment] 2019-06-26 21:37
Duplicate of #225

I know its a bit different, but its a related issue, going to use that one as the issue on the subject.

**Closed by ykeara** 2019-06-26 21:37 UTC
