### ISSUE TITLE
Everything stops working once in a game.

### ISSUE THREAD

**Issue by BortSimpin** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#215] opened 2019-06-04 20:40 UTC
Everything works fine in steam vr and steam vr home. But once i open a game, nothing works. I'm using an oculus rift.

**Comment by ykeara** [comment] 2019-06-04 20:43
Do you know if the Game is using the Oculus API vs SteamVR/OpenVR.... if that is the case this is probably the issue as SteamVR/OpenVR is technically not running and therefore ADV Settings might not be running.

**Comment by BortSimpin** [comment] 2019-06-04 20:45
> Do you know if the Game is using the Oculus API vs SteamVR/OpenVR.... if that is the case this is probably the issue as SteamVR/OpenVR is technically not running and therefore ADV Settings might not be running.

How do i make it use the openVR api?

**Comment by ykeara** [comment] 2019-06-04 20:52
If a unity game try startup param of -vrmode openvr

possibly https://www.reddit.com/r/oculus/comments/8gfktd/psa_beat_saber_on_steam_native_oculus_support/

Don't know about UE4.

**Comment by BortSimpin** [comment] 2019-06-04 20:55
Damn, it's a UE4 game

**Comment by BortSimpin** [comment] 2019-06-04 21:24
is there anything i can do?

**Comment by ykeara** [comment] 2019-06-04 21:28
Try some other games that you know don't use the oculus API, verify it works in those, see the reddit link above about blocking  Oculus tray tool and such.

I may be wrong in my guess, but that appears to be the issue, and if the issue is only persistent in 1 game that is the most likely issue. But if there is no way to get that specific game to run w/ openvr/steamVR then the ultimate answer is no, as OVRAS relies on it.

**Comment by ykeara** [comment] 2019-06-05 18:30
Closing issue as it appears its "resolved" if it comes down to being an issue w/ further testing on our end will re-open.

**Closed by ykeara** 2019-06-05 18:30 UTC
