### ISSUE TITLE
Control Height

### ISSUE THREAD

**Issue by Haleirwin** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#283] opened 2019-08-25 09:14 UTC
Hello, i have problem with height (im using Lenovo Explorer, WMR) in certain games (moss, pinball fx2, bigscreen vr) but using the openvr advanced settings v2.5 all works fine (the feature accessibility with height parameter), but this release not contains video section for brightness. Can you add accesibility settings for configure properly height? Thanks a lot.

**Comment by ykeara** [comment] 2019-08-25 20:31
duplicate of #170 closing this issue in favor of it.

(up to 2.8.0 should work for you, and we are aware of the issue, if you play with your boundary on in WMR it should fix some of the issues.)

**Closed by ykeara** 2019-08-25 20:31 UTC
Labels: enhancement
