### ISSUE TITLE
Prevents 3rd party chaperone editing and resetting seated position

### ISSUE THREAD

**Issue by VsevolodGolovanov** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#147] opened 2019-04-03 16:43 UTC
Version 3.0.1.
HTC Vive, Windows 10.

3.0.0 messed up my play space and chaperone positions, so I downloaded 3.0.1 as suggested in the release notes, and went through room setup. The room setup itself worked fine.

Afterwards I tried editing the chaperone with ChaperoneTweak, but when I tried to save, instead it cancelled my changes.

Then I started Elite Dangerous, and discovered that in-game resetting seating position (F12 by default) doesn't work either. It has no effect at all.

After disabling Advanced Settings both problems went away.

**Comment by ykeara** [comment] 2019-04-03 17:03
Duplicate of #145, we are aware of the issue, and are working on it...  If you need some features going back to 2.8.0 will fix it for the time being.

**Comment by ykeara** [comment] 2019-04-03 20:17
Closing In favor of consolidation for #145

**Closed by ykeara** 2019-04-03 20:17 UTC

**Comment by Kung-vr** [comment] 2019-04-11 19:45
Seated recenter should be solved in 145, but third party chaperone editing is not supported at this time and may not get support added. This is because chaperone is handled in absolute terms now (for safety) and relative changes from other apps can't be folded in easily.
