### ISSUE TITLE
Chaperone Profiles Constantly Reset/Break

### ISSUE THREAD

**Issue by spoonyspork** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#450] opened 2020-05-18 01:11 UTC
**Describe the bug**
I use a WMR HMD with Index controllers. I had OVRAS copy the boundary from WMR space and saved it to a profile. It always works the first time, but after restarting SteamVR, enabling the profile again doesn't seem to work. Sometimes it will throw me into the ground, sometimes random settings will be enabled that weren't enabled before, sometimes there's suddenly an extra copy of the profile (both broken in the same way), sometimes the geometry just turns into a triangle. I have found that if I completely reboot the computer before going into SteamVR again, most of the time the profile still works, though sometimes random settings will still be enabled. Also if I try to delete profiles, the next time SteamVR starts a number of profiles named 'previous' will then be in the list, all with random settings enabled. The number that appear are the number of profiles that were deleted.

**To Reproduce**
1. Copy WMR chaperone bounds into OVRAS (this can be done either via space calibrator and telling OVRAS chaperone to 'reset to disk' with 'allow external apps chaperone edits' checked, or just going into OVRAS before calibrating the Index controllers and saving a chaperone profile with the current WMR settings also seems to work)
2. With calibrated Index controllers on and WMR controllers off, pick the settings you want OVRAS to use (in my example, I just want 'play space', 'geometry', and 'proximity warnings', but when saving the profile I check all the boxes to be saved so the ones I *didn't* want on show that they aren't on)
3. Play some games. Note they all work. Exit SteamVR
4. Open SteamVR again. Either from WMR's cliffhouse, or the desktop. Click the profile you want to use. Watch it break in many different ways. Note that games that rely on the chaperone to work do not work (two examples: Until you Fall and Lone Echo. Until you Fall won't allow controller input, and Lone Echo throws you somewhere random in the start menu)
5. Create another profile based on the originally created profile. It will not work, but note it *looks* correct.
6. Restart PC. Start SteamVR. Pick the newly created profile. Note it works as expected though sometimes random settings are on or off that were not when you created the profile. If you pick the other profile, it has probably turned into nothing but a triangle. Delete it.
7. Restart PC. Start SteamVR. So long as you had not restarted SteamVR without restarting the PC first, the last saved profile should work as expected, though again possibly with some random settings turned on or off. Note there is now an extra profile named 'previous'. Delete that... and maybe delete any others that may have been there in the past.
8. Repeat with same results each time.

**Expected behavior**
Saved profiles to stick to the saved settings, and to work without needing a PC reboot. Deleted profile to actually delete.

**Screenshots**
See https://imgur.com/a/GpLThW2

**Software (please complete the following information):**
 - OS: Windows 10 build 1909
 - Advanced Settings Version: 5.1.0 (same things were happening since 5.0.0 release but not on 4.0.1 -- I have been working this out for a month)

**Hardware (please complete the following information):**
 - CPU: i7 7700k, R7 3800x
 - Graphics Card: 1070ti, 2080
 - HMD: Samsung Odyssey +

**Additional context**
While my setup is a bit weird, I am not sure if the behavior is really related to that? I have OVRAS set up so it *shouldn't* be getting clashes with other settings. See https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/issues/426 for previous issue (I had noticed the odd thing with trying to delete profile resulting in a mostly broken new profile being created instead but thought that was related to... that previous issue) which I was able to work through. I had been using this setup for more than a year prior (had Vive wands previous to Index controllers as well) with absolutely zero issues. Space Calibrator plopped me into the correct general area and clicking the saved OVRAS profile got me a proper-working steamVR chaperone so I could play all games without issues. Had set this up on several different PCs and rooms without issues on any of them. Never even had to recalibrate spaces or anything: just set it up the first time and played away. Not sure what changed where.

I have a somewhat broken WMR set (screen cracked at the top but works otherwise) I'd be happy to send a dev if it's an issue of equipment! I also have some experience with C++ and have a dev environment set up to try and debug, but have no idea of where to start looking in the code as I have no idea how everything interfaces together. Hints in that direction would also be helpful!

**Comment by ykeara** [comment] 2020-05-18 02:14
some of the new versions of OVR have some new integration with WMR so maybe I should look into that : /

It's also possible our new settings system has some sort of bug as its new in 5.0.0

The floor bounds always on was not active in 5.0.1 and 5.0.2 saving profiles at that point wouldn't have actually saved it... (should have always been false)

so could get logs from %appdata%/advancedsettings-team both files (one is setting one is log) if you can upload here.

I don't understand 5? can you re-word?

I would turn off "automatic chaperone recovery" as well in settings.

now we 100% save to disk when you exit steamvr (often before that) so that is leading me to believe that at least WMR is playing some role.


I'm leaning towards it primarily being an issue with our new settings system. I'll try to set up a similiar environment this week ( I have an O+) and see what I can figure out.

as for your DEV environment do you have QT installed... you will need to use it to debug and compile for that matter.

But giving you a brief rundown. profiles and settings are defined in settings folders.

Now the reality is most if not all of the logic is happening in the `chaperonetabcontroller`.

and also curious to see what happens if you delete your settings and start with a clean one.

**Comment by spoonyspork** [comment] 2020-05-18 02:47
Ah yeah -- it was 'force bounds' (on the same page as 'play space' as seen [here](https://i.imgur.com/mQuMzNN.jpg) ) that would sometimes turn on instead. 'Floor bounds always on' and 'force bounds' seems to do the same thing.

For 5... when I've restarted SteamVR but not the PC, and the profile I've clicked is broken in some way (such as I'm in the floor), if I do a floor fix and save another profile, it looks correct (I can see the playspace on the ground, I'm in the correct place in the room, etc), but if I start a game that relies on the chaperone, said game doesn't work. After a reboot, setting that profile works.

If by 'turn off automatic chaperone recovery' you mean the check box that says 'disable automatic crash recovery of chaperone config' ... that is already checked.

I do not have QT: just Visual Studio. I've been slowly skimming through the code. Going to focus on chaperonetabcontroller and look into QT!

For that last bit: this is actually what I got after completely blowing out everything I could find having to do with Steam, SteamVR, or OpenVR (uninstalled everything, deleted folders, searched through appdata, etc). I also cleared out room data from WMR before starting over again.

I also put a completely new HD into one of my PC's and set up completely fresh from a virgin windows install, and got even weirder issues. OpenVR space calibrator calibrates the controllers fine, but 'paste chaperone bounds' won't stick, even without OVRAS installed ever. As such I can't seem to copy over WMR's chaperone bounds to OVRAS so can't test further. I did get it to get the WMR bounds once but at that point I was suddenly getting... many chaperone profiles called 'previous' so gave up and went back to this install. I have no idea why it gives different behavior starting from a fresh install, since I've deleted literally *everything* I could find referencing anything having to do with VR on this install before trying the setup again.

**Comment by ykeara** [comment] 2020-05-18 23:56
I can confirm profiles are a glorious mess on WMR. I'm thinking that WMR is passing SteamVR un-defined values on our calls. I'm drawing up a testing plan to see exact behavior but looks like there are 2 or 3 issues.... my guess the solution long term will be force using the chaperone but I'll see what happens.

**Comment by spoonyspork** [comment] 2020-05-19 00:01
Oh thank goodness I am not just going crazy!

The strangest thing (to me) is that it almost *always* works with a complete reboot of the PC. I've tried seeing what might still be running in the background to cause it not to work just restarting SteamVR, but nothing pops out at me.

Word of warning: it seems to do something similar with Oculus Quest (both connected wirelessly and through Link)

**Comment by spoonyspork** [comment] 2020-05-20 21:57
[AdvancedSettings.log](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings/files/4659459/AdvancedSettings.log)
Still poking around today... reading through the log and thought it might be useful for something? I'm trying to figure out the game that triggers that flurry of '[INFO] 2020-05-02 13:26:08: Game Triggered Seated Zero-Position Reset' (none of my games use seated mode IIRC, but I have a feeling that happens when I try to run one of those games that breaks when the chaperone isn't correct)

I also *think* the '[WARNING] 2020-05-15 17:38:23: QTMSGH: file:///C:/Program Files/OpenVR-AdvancedSettings/res/qml/chaperone_page/chaperone_additional/chaperonemisc/ChaperoneMiscGroupBox.qml:77: Error: Cannot assign [undefined] to bool' is trigger when I've restarted steamVR without rebooting the PC but will need to test a bit further...

**Comment by ykeara** [comment] 2020-05-21 04:03
got [WARNING] 2020-05-15 17:38:23: QTMSGH: file:///C:/Program Files/OpenVR-AdvancedSettings/res/qml/chaperone_page/chaperone_additional/chaperonemisc/ChaperoneMiscGroupBox.qml:77: Error: Cannot assign [undefined] to bool... Fixed now good catch... was calling `.centermarker` not `.centerMarker` but shouldn't be effecting anything

**Comment by spoonyspork** [comment] 2020-05-28 22:09
Me again! I think this issue may be 'playspace' and 'chaperone bounds' being applied incorrectly and one is being confused for the other somewhere. Maybe in OVRAS, maybe in SteamVR, maybe in the WMR layer. Leaning toward one of the later two because nothing is jumping out at me in the code for OVRAS.

Let me see if I can explain the behavior so it makes sense...

If I have WMR's chaperone bounds copied over to OVRAS, if I tell it to turn on floor bounds, it gives me an area shaped like WMR's chaperone bounds

If I turn on playspace, I also get an area shaped like the WMR chaperone

However, if I use a native steamVR HMD (Index, Vive), if I turn on floor bounds I just get a box (just a plain big square on the ground roughly the size of the playspace). If I turn on playspace I get an outline shaped like what I set up with room setup in steamVR.

So I feel like one of the two may be getting confused with WMR? I'm not sure I've described this well... I can try and reword if not!

**Comment by ykeara** [comment] 2020-05-31 21:28
@spoonyspork  Pushed an update to beta Branch on Steam (or grab the build from xormisc branch), see if you can try it out. We fixed an issue with saving chaperone profiles (you will probably need new ones)

This May/May not be the issue, but Just need to know if this fixed it or if we need to look at WMR specifically. (ded7e3b9 is what you should see in version)

**Comment by ykeara** [comment] 2020-06-07 06:55
Going to close out Issue as it appears to be resolved in #459

**Closed by ykeara** 2020-06-07 06:55 UTC
Labels: bug
