### ISSUE TITLE
Z-scale is very useful for short people

### ISSUE THREAD

**Issue by ibubbleball** [OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#296] opened 2019-10-18 12:17 UTC
Can you add z-scale function for short people.

I just test z-scale of cybershoes and this is very useful when I sit on the chair, but character still stand. When I touch on the floor, the character can touch the floor too.

My kid still be short and when he play a game which have to get the item on the high postion, I have to adjust the height for him, when item drop to the floor, he can't get the item because the floor is too low.

So I hope we can use this function in openvr-advancedsetting.

Thank you.

**Comment by Kung-vr** [comment] 2019-10-18 14:51
I looked at a video of cybershoes z-scale but I can't see exactly what it's doing. Is that a change to ipd-scale (world scale)? Or does it keep the same scale but make up and down movements of your head move your further? We can't change ipd but it might be possible to amplify head movements. 

If you're looking for a solution right now, have you tried our "height toggle" feature in the motion tab? It's possible to set a binding in steamvr input config for that. It would allow your child to press a button on the controller to snap up and down by any set distance that fits for him.

**Comment by username223** [comment] 2019-11-03 12:53
Referencing [this](https://www.youtube.com/watch?v=4s0jtK3tvGc) video and [this](https://www.youtube.com/watch?v=ro7CiBlflWE) video.

It seems like the problem is that most games are made under the assumption that you will be able to reach objects on something the height of a table without issue. The problem comes when you are either sitting or not very tall.

The common "solution" to this is to offset the actual height of the sitting player to an ideal height, however now the in game floor is below the real floor, and you can't pick up items from the virtual floor.

Z-Scaling seems to map your actual height (say 0m to 1.2m) to an in game height (say 0m to 1.8m) percentage wise. Note that this conversion would have to happen for all tracked devices.

I am not sure whether Z-Scaling could be implemented without using drivers, or whether it falls within the scope of Advanced Settings.
___

@ibubbleball your specific issue could be solved with the solution Kung offered. On the [motion page](https://github.com/OpenVR-Advanced-Settings/OpenVR-AdvancedSettings#--motion-page) there is a Height Toggle that can also be bound to a VR controller button via the Steam controller bindings.

**Comment by ykeara** [comment] 2019-11-10 19:13
Closing Out. As addressed the ability within the scope of our project is more or less implemented, a more advanced implementation would require a driver.

**Closed by ykeara** 2019-11-10 19:13 UTC
Labels: enhancement
